(cl:defpackage simple_navigation_goals-msg
  (:use )
  (:export
   "<TURTLEMOVEACTION>"
   "TURTLEMOVEACTION"
   "<TURTLEMOVEACTIONFEEDBACK>"
   "TURTLEMOVEACTIONFEEDBACK"
   "<TURTLEMOVEACTIONGOAL>"
   "TURTLEMOVEACTIONGOAL"
   "<TURTLEMOVEACTIONRESULT>"
   "TURTLEMOVEACTIONRESULT"
   "<TURTLEMOVEFEEDBACK>"
   "TURTLEMOVEFEEDBACK"
   "<TURTLEMOVEGOAL>"
   "TURTLEMOVEGOAL"
   "<TURTLEMOVERESULT>"
   "TURTLEMOVERESULT"
  ))

