// Generated by gencpp from file simple_navigation_goals/TurtleMoveResult.msg
// DO NOT EDIT!


#ifndef SIMPLE_NAVIGATION_GOALS_MESSAGE_TURTLEMOVERESULT_H
#define SIMPLE_NAVIGATION_GOALS_MESSAGE_TURTLEMOVERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_navigation_goals
{
template <class ContainerAllocator>
struct TurtleMoveResult_
{
  typedef TurtleMoveResult_<ContainerAllocator> Type;

  TurtleMoveResult_()
    : turtle_final_x(0.0)
    , turtle_final_y(0.0)
    , turtle_final_theta(0.0)  {
    }
  TurtleMoveResult_(const ContainerAllocator& _alloc)
    : turtle_final_x(0.0)
    , turtle_final_y(0.0)
    , turtle_final_theta(0.0)  {
  (void)_alloc;
    }



   typedef double _turtle_final_x_type;
  _turtle_final_x_type turtle_final_x;

   typedef double _turtle_final_y_type;
  _turtle_final_y_type turtle_final_y;

   typedef double _turtle_final_theta_type;
  _turtle_final_theta_type turtle_final_theta;





  typedef boost::shared_ptr< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleMoveResult_

typedef ::simple_navigation_goals::TurtleMoveResult_<std::allocator<void> > TurtleMoveResult;

typedef boost::shared_ptr< ::simple_navigation_goals::TurtleMoveResult > TurtleMoveResultPtr;
typedef boost::shared_ptr< ::simple_navigation_goals::TurtleMoveResult const> TurtleMoveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_navigation_goals

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'move_base_msgs': ['/opt/ros/kinetic/share/move_base_msgs/cmake/../msg'], 'simple_navigation_goals': ['/home/winkle/sim/my_ws/devel/share/simple_navigation_goals/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e7b4195ae4864a401f0242e01596152";
  }

  static const char* value(const ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e7b4195ae4864a4ULL;
  static const uint64_t static_value2 = 0x01f0242e01596152ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_navigation_goals/TurtleMoveResult";
  }

  static const char* value(const ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
float64 turtle_final_x\n\
float64 turtle_final_y\n\
float64 turtle_final_theta\n\
";
  }

  static const char* value(const ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turtle_final_x);
      stream.next(m.turtle_final_y);
      stream.next(m.turtle_final_theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleMoveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_navigation_goals::TurtleMoveResult_<ContainerAllocator>& v)
  {
    s << indent << "turtle_final_x: ";
    Printer<double>::stream(s, indent + "  ", v.turtle_final_x);
    s << indent << "turtle_final_y: ";
    Printer<double>::stream(s, indent + "  ", v.turtle_final_y);
    s << indent << "turtle_final_theta: ";
    Printer<double>::stream(s, indent + "  ", v.turtle_final_theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_NAVIGATION_GOALS_MESSAGE_TURTLEMOVERESULT_H
